# AWS Configuration
aws.region=us-east-1
aws.dynamodb.table-name=ItemVariants
aws.s3.bucket-name=item-variant-details-846497880922
aws.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/846497880922/item-variant-queue

# Disable default embedded server (Lambda handles HTTP)
spring.main.web-application-type=servlet
