# SFTP Configuration
sftp.host=us-east-1.sftpcloud.io
sftp.port=22
sftp.username=0e0f99d70fe84a92a5a36c633ecb131b
sftp.password=XLbGYeMdvQaONyKXaE1JDS9sYy1WU3Kj
sftp.remote-path=/PROD_INPUT.TXT

# AWS Configuration
aws.region=us-east-1
aws.s3.bucket-name=item-variant-details-846497880922
aws.s3.key-prefix=sftp-output
aws.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/846497880922/item-variant-queue
